# -*- coding: utf-8 -*-
"""Project 2 (Predictive Modeling for Attorney Involvement in Claims).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8sFH0bDL0v1eG6eRZgIChL3CjlJwWDF
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.read_csv("Updated_Claimants_Dataset.csv")

df.head(15)

df.tail(15)

df.info()

df.describe()

print(df.isnull().sum())

sns.countplot(data=df, x="ATTORNEY")
plt.title('ATTORNEY INVOLVEMENT DISTRIBUTION')
plt.show()
print(df.count())

df[["CLMAGE","LOSS","Claim_Amount_Requested","Settlement_Amount"]].hist(bins=15, figsize=(12,8))
plt.tight_layout()
plt.show()

df['Accident_Severity'] = df['Accident_Severity'].astype(str)
df['ATTORNEY'] = df['ATTORNEY'].astype(str)


sns.countplot(data=df, x="Accident_Severity", hue="ATTORNEY")
plt.title('ACCIDENT SEVERITY VS ATTORNY INVOLVEMENT')
plt.legend()
plt.show()

from sklearn.preprocessing import LabelEncoder

categorical_cols = ['Accident_Severity', 'Policy_Type', 'Driving_Record']
label_encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le


df_corr = df.corr()

sns.heatmap(data=df_corr, annot=True, fmt=".2f", cmap='coolwarm')
plt.title("CORRELATION HEATMAP")
plt.show()

df.isnull().sum()

numerical_cols = df.select_dtypes(include=['number']).columns
df[numerical_cols] = df[numerical_cols].fillna(df[numerical_cols].median())

categorical_cols = df.select_dtypes(include=['object']).columns
df[categorical_cols] = df[categorical_cols].fillna(df[categorical_cols].mode().iloc(0))

df.isnull().sum()

df.info()

print(numerical_cols)
print(categorical_cols)

plt.figure(figsize=(28,8))
sns.boxplot(df)
plt.title('BOXPLOT')
plt.show()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
numerical_cols = ['CLMAGE', 'LOSS', 'Claim_Amount_Requested', 'Settlement_Amount']
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

x = df.drop(columns = ['ATTORNEY','CASENUM'])
y = df['ATTORNEY']

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.2, random_state=42)

!pip install sweetviz

import sweetviz as sv

report = sv.analyze(df)
report.show_html("sweetviz_report(Project 2 (Predictive Modeling for Attorney Involvement in Claims)).html")

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

log_reg = LogisticRegression()
log_reg.fit(X_train,Y_train)
Y_pred_log = log_reg.predict(X_test)
print("Logistical Regression :", accuracy_score(Y_test, Y_pred_log))

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.metrics import classification_report, roc_curve, auc, accuracy_score, precision_score, recall_score, f1_score
import numpy as np

models = {
    "Linear Regression":LinearRegression(),
    "Ridge Regression":Ridge(),
    "Lasso Regression":Lasso(),
    "ElasticNet": ElasticNet(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(),
    "Gradient Boosting": GradientBoostingRegressor(),
    "AdaBoost": AdaBoostRegressor(),
    "SVR":SVR(),
    "XGBoost": XGBRegressor(),
}

results=[]
for name, model in models.items():
    model.fit(X_train, Y_train)
    Y_pred = model.predict(X_test)


    rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))
    mae = mean_absolute_error(Y_test, Y_pred)
    r2 = r2_score(Y_test, Y_pred)

    results.append((name, rmse, mae, r2))


print(f"{'Model':<25} {'RMSE':<10} {'MAE':<10} {'R2':<10}")
print("-" * 50)
for name, rmse, mae, r2  in sorted(results, key=lambda x: x[1]):
    print(f"{name:<25} {rmse:<10.4f} {mae:<10.4f} {r2:<10.4f}")

import pickle

"""with open("linear_model.pkl", "wb") as f:
    pickle.dump(LinearRegression, f)
    
with open("ridge_model.pkl", "wb") as f:
    pickle.dump(Ridge, f)
"""

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, roc_curve, auc
)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import pandas as pd

# Define models
models = {
    "Logistic Regression": LogisticRegression(),
    "Random Forest": RandomForestClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Support Vector Machine": SVC(probability=True)  # `probability=True` for ROC AUC
}

results1 = {}

for name, model in models.items():
    # Train the model
    model.fit(X_train, Y_train)

    # Predict test set labels and probabilities
    Y_pred = model.predict(X_test)
    Y_prob = model.predict_proba(X_test)[:, 1] if hasattr(model, "predict_proba") else None

    # Convert `Y_test` and `Y_pred` to strings to ensure compatibility
    Y_test_str = Y_test.astype(str)
    Y_pred_str = Y_pred.astype(str)

    # Calculate metrics
    accuracy = accuracy_score(Y_test_str, Y_pred_str)
    precision = precision_score(Y_test_str, Y_pred_str, pos_label='1')
    recall = recall_score(Y_test_str, Y_pred_str, pos_label='1')
    f1 = f1_score(Y_test_str, Y_pred_str, pos_label='1')

    # Store results
    results1[name] = {
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1
    }

    # Plot ROC Curve (if probabilities are available)
    if Y_prob is not None:
        fpr, tpr, _ = roc_curve(Y_test.astype(int), Y_prob)
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, label=f"{name} (AUC = {roc_auc:.2f})")

# Finalizing the AUC plot
plt.title("ROC Curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend(loc="lower right")
plt.show()

# Display the results as a DataFrame
print(pd.DataFrame(results1).T)

import pickle

# Save the trained models
with open('models.pkl', 'wb') as file:
    pickle.dump(models, file)

import pickle
from sklearn.linear_model import LogisticRegression

# Assuming X_train and Y_train are already defined
logistic_model = LogisticRegression()

# Train the Logistic Regression model
logistic_model.fit(X_train, Y_train)

# Save the trained model using pickle
filename = 'logistic_model.pkl'
pickle.dump(logistic_model, open(filename, 'wb'))

# Print confirmation
print(f"Logistic Regression model saved to {filename}")

